### ISSUE TITLE
consider moving away from github pages to get ssl

### ISSUE THREAD

**Issue by sethvincent** [openseattle/openseattle.github.io#12]
surge.sh could be an option.

or s3 + cloudfront.

or a simple server running nginx.

but ssl would be nice to have. maybe not essential since there's no logins on this site yet.

**Comment by timothyclemansinsea** [comment]
I use Cloudflare and Github pages with https://sodaplayground.com I have a page rule to force HTTPS

**Comment by BenRuns** [comment]
I had a thought about this.  S3 + cloudfront seems like a good option for  just the simple ease of setting up ssl.  One disadvantage would be sacrifices the lack of a deployment step with the current setup. I think, that could be kept if we use something like Circle CI to build and deploy when changes are made to the master/gh-pages branch.  After initial setup, there should be not be any changes noticeable to current contributors.

### Steps to do this
1.  Setup an OpenSeattle AWS account if one does not exist
2.  Set up and Configure CircleCI account to build and deploy to an S3 + cloudfront setup when changes are made to the master on github
3.  Move the domain over to AWS and add an SSL cert 

I've got some time to work out the details and set it up if there's interest,  although, I'd need help with the AWS account / domain transfers from the current organizers.

**Comment by sllvn** [comment]
As of mid-2018, GH pages support SSL. Reached out to Seth and he updated DNS settings enabling this, and I just switched on SSL! :tada:
