### ISSUE TITLE
some links don't work

### ISSUE THREAD

**Issue by smarts** [openseattle/openseattle.github.io#21]
Some links (like that for Pulleykingcounty) do not work because they are relative URLs.

**Comment by ptressel** [comment]
I bet they'd like a PR.  ;-)

**Comment by smarts** [comment]
And I'd be happy to give one but I'm not Jekyll/Ruby fluent. I researched a bit and it appeared the best solution would be a filter applied to the URL. Maybe one already exists?
Alternatively I could correct the broken links in the data itself, but that's not a long-term solution.

**Comment by smarts** [comment]
Now I'm convinced it wouldn't matter if I had submitted a pull request. No one has acknowledged the issue in over 2 months.

**Comment by modulitos** [comment]
Seems like the Pulley King Co. project wasn't active or got removed from the list of projects. Closing this issue for now...
