### ISSUE TITLE
`bundle exec jekyll serve` goes through an infinite loop on auto-regeneration

### ISSUE THREAD

**Issue by modulitos** [openseattle/openseattle.github.io#38]
**Repro:**
 * Start the server with `bundle exec jekyll serve`.
 * Edit any file and save it. (ie `echo "<div>yay</div>" >> index.html`)
 * You'll get output like this:
   ```
   [my-pc]/home/.../websites/openseattle.github.io$ bundle exec jekyll serve
   Configuration file: /home/lucas/projects/websites/openseattle.github.io/_config.yml
               Source: /home/lucas/projects/websites/openseattle.github.io
          Destination: /home/lucas/projects/websites/openseattle.github.io/_site
    Incremental build: disabled. Enable with --incremental
         Generating...
                       done in 0.616 seconds.
    Auto-regeneration: enabled for '/home/lucas/projects/websites/openseattle.github.io'
   Configuration file: /home/lucas/projects/websites/openseattle.github.io/_config.yml
       Server address: http://127.0.0.1:4000/
     Server running... press ctrl-c to stop.
         Regenerating: 2 file(s) changed at 2017-06-04 19:40:58 ...done in 0.485150987 seconds.
         Regenerating: 1 file(s) changed at 2017-06-04 19:40:59 ...done in 0.45860538 seconds.
         Regenerating: 1 file(s) changed at 2017-06-04 19:41:00 ...done in 0.482768408 seconds.
         Regenerating: 1 file(s) changed at 2017-06-04 19:41:00 ...done in 0.46793245 seconds.
         Regenerating: 1 file(s) changed at 2017-06-04 19:41:01 ...done in 0.466628054 seconds.
   ```
   which regenerates forever and ever...

**Expected:**
It should only trigger a single regeneration for that file.

**Update:**
t looks like this is caused by the [jekyll-json](https://github.com/BenRuns/jekyll-json/blob/development/lib/jekyll-json.rb#L29) plugin, which writes out a new `.csv` file on change, causing jekyll to regenerate the site again, causing `jekyll-json` to write out a new `.csv` file again, causing jekyll to regenerate the site again, etc...

**Comment by BenRuns** [comment]
We were original generating the files in csv so that code for america could scrape them or something. Not sure if that is still the case. Don't think the infinite loop should be a problem on gh-pages since the gems they load wouldn't include jekyll-json. If the csv files are still needed, I'll fix the gem.
