### ISSUE TITLE
Featured projects should be clickable

### ISSUE THREAD

**Issue by modulitos** [openseattle/openseattle.github.io#40]
Projects on the home page should be clickable:

![2017-06-05-192024_1090x729_escrotum](https://cloud.githubusercontent.com/assets/4207017/26811086/6a3b53be-4a24-11e7-8cd8-1134f51ae5db.png)

**Comment by ammiranda** [comment]
@LukeSwart Can this issue be closed? I see that the featured projects on the main page are now clickable links.

**Comment by modulitos** [comment]
Thanks @ammiranda 
Closing now...

**Comment by ammiranda** [comment]
You are welcome! Just looking for something to help with! :)
